### ISSUE TITLE
JAVA TreeMap高并发下异常分析

### ISSUE THREAD

**Issue by niepantzy** [serverBiatch/teamWiki#17]
# JAVA TreeMap高并发下异常分析

> 前几天国内挂机线上服又出线了cpu100%的情况，然后@crazyJohn定位到是ExpeditionArmoryManager中使用线程不安全的TreeSet导致的。而且近期海外挂机那边也出现过类似的情况，也是在并发情况下使用TreeSet导致cpu100%。之前对线程不安全的理解就是多个线程访问同一对象会导致数据不完整或者说数据混乱，并不知道还会导致这种情况，去网上查资料发现HashMap高并发下使用会导致死循环，具体原因[在这里](http://blog.csdn.net/xiaohui127/article/details/11928865)，但是有关TreeSet高并发使用会导致什么网上并没有什么资料，所以只能自己去看了，下面是我自己查找问题的一个过程，可能还不完善，边找边完善吧

---
## 1. TreeMap和TreeSet之间的关系

   貌似在java中，Set底层其实都是Map去实现的，这个我没有做全部验证，只看过HashMap和HashSet的源码是这样实现，下面是TreeSet的部分源码：

``` java
    private transient NavigableMap<E,Object> m;

    // Dummy value to associate with an Object in the backing Map
    private static final Object PRESENT = new Object();

    /**
     * Constructs a set backed by the specified navigable map.
     */
    TreeSet(NavigableMap<E,Object> m) {
        this.m = m;
    }
    public TreeSet() {//无参构造函数
        this(new TreeMap<E,Object>());
    }
     public TreeSet(Comparator<? super E> comparator) {// 包含比较器的构造函数
        this(new TreeMap<>(comparator));
    }

     public TreeSet(Collection<? extends E> c) {
        this();
        addAll(c);
    }

    public TreeSet(SortedSet<E> s) {
        this(s.comparator());
        addAll(s);
    }
```

这里构造函数相关部分的代码看起来比较多，实际上主要的构造函数就两个，一个是默认的无参数构造函数和一个比较器构造函数，他们内部的实现都是使用的TreeMap，而其他相关的构造函数都是通过调用这两个来实现的，故其底层使用的就是TreeMap。既然TreeSet只是TreeMap的一个马甲，我们就只要重点关注一下TreeMap里面的实现好了。
## 2.  场景重现

我分别试了TreeMap在多线程下的put和remove，下面先贴上测试代码：

``` java
public class TestTreeMap {

    public static void main(String[] args) {
        final Map<Integer, Integer> m=new TreeMap<Integer,Integer>();
      //        for (int i = 0; i < 10000; i++) {
      //            m.put(i, i);
      //        }

        for (int i = 1; i <= 10; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int j = 1; j <= 10000; j++) {
                        m.put(j, j);
      //                m.remove(j);
                    }
                }
            }).start();
        }
    }
    }
```

一、先说TreeMap的put重现结果，会出现四种情况：
1. 正常执行完毕 
2. 部分线程报空指针其他线程执行完毕
3. 部分线程报空指针部分线程进入死循环
4. 部分线程进入死循环
   下面把后三种情况的报错情况以及堆栈信息贴出来（我是在windows环境下进行的测试，没有找到Linux下类似top的指令，但是我的业务逻辑很简单，就是自己启动的10个线程，所以也不需要去定位到底是哪个线程跑满cpu,直接看堆栈就可以）,这些堆栈信息都是经过多次截取，基本一致：

2>>部分线程报空指针其他线程执行完毕:

``` java
//console log
Exception in thread "Thread-1" java.lang.NullPointerException
at java.util.TreeMap.rotateLeft(TreeMap.java:2060)
at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2127)
at java.util.TreeMap.put(TreeMap.java:574)
at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
at java.lang.Thread.run(Thread.java:745)
```

3>>部分线程报空指针部分线程进入死循环 

``` java
    //console log
    Exception in thread "Thread-9" java.lang.NullPointerException
    at java.util.TreeMap.rotateLeft(TreeMap.java:2060)
    at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2127)
    at java.util.TreeMap.put(TreeMap.java:574)
    at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
    at java.lang.Thread.run(Thread.java:745)
```

```
    //jps查询PID
    C:\Users\Administrator>jps
    8224 Jps
    9636 TestTreeMap
    8456 org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
    7460 org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
```

```
    //jstack 打出堆栈信息
    C:\Users\Administrator>jstack -l 9636

    2015-08-21 12:23:04
    Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.60-b09 mixed mode):

    "DestroyJavaVM" prio=6 tid=0x000000000241e000 nid=0x1068 waiting on condition [0x0000000000000000]
       java.lang.Thread.State: RUNNABLE

       Locked ownable synchronizers:
        - None

    "Thread-8" prio=6 tid=0x000000000c5b7000 nid=0x2044 runnable [0x000000000db1f000]
       java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:567)
        at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
        at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
        - None

    "Thread-7" prio=6 tid=0x000000000c5b4800 nid=0x2454 runnable [0x000000000d9ef000]
       java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:567)
        at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
        at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
        - None

    "Thread-4" prio=6 tid=0x000000000c5af000 nid=0x23d0 runnable [0x000000000d54e000]
       java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:567)
        at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
        at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
        - None

    "Thread-3" prio=6 tid=0x000000000c5ae000 nid=0x2574 runnable [0x000000000d37e000]
       java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:567)
        at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
        at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
        - None

    "Thread-2" prio=6 tid=0x000000000c5a9000 nid=0x2744 runnable [0x000000000d17f000]
       java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:567)
        at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
        at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
        - None

    "Thread-0" prio=6 tid=0x000000000c5a3800 nid=0x2750 runnable [0x000000000cf2f000]
       java.lang.Thread.State: RUNNABLE
        at java.util.TreeMap.put(TreeMap.java:567)
        at testTreesett.TestTreeMap$1.run(TestTreeMap.java:19)
        at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
        - None

    ....//后面其他线程的堆栈信息省略
```

第四种情况打出的堆栈信息和上面第三种的差不多就不多占版面贴出来了。

二、 下面是TreeMap的remove重现结果，会出现两种情况：
1. 正常执行完毕 
2. 部分线程进入死循环
   下面贴出进入死循环后的堆栈信息：

```
    //jstack 打出堆栈信息
    C:\Users\Administrator>jstack -l 9636
    2015-08-21 11:06:12
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.60-b09 mixed mode):

"DestroyJavaVM" prio=6 tid=0x000000000c669800 nid=0x193c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-2" prio=6 tid=0x000000000c663800 nid=0x23e8 runnable [0x000000000d39e000]
   java.lang.Thread.State: RUNNABLE
    at java.util.TreeMap.fixAfterDeletion(TreeMap.java:2215)
    at java.util.TreeMap.deleteEntry(TreeMap.java:2168)
    at java.util.TreeMap.remove(TreeMap.java:600)
    at testTreesett.TestTreeMap$1.run(TestTreeMap.java:29)
    at java.lang.Thread.run(Thread.java:745)

"Thread-1" prio=6 tid=0x000000000c662800 nid=0x16fc runnable [0x000000000d23e000]
   java.lang.Thread.State: RUNNABLE
    at java.util.TreeMap.fixAfterDeletion(TreeMap.java:2215)
    at java.util.TreeMap.deleteEntry(TreeMap.java:2173)
    at java.util.TreeMap.remove(TreeMap.java:600)
    at testTreesett.TestTreeMap$1.run(TestTreeMap.java:29)
    at java.lang.Thread.run(Thread.java:745)

    ...//后面其他线程的堆栈信息省略
```

这里还有一张@芒果提供的线上服堆栈信息截图：
![](http://i.imgur.com/oSwDJws.jpg)
## 3.  红黑树简介

由于TreeMap内部使用到了红黑树来实现排序，所以去找了资料学习红黑树，这里先把红黑树的定义给出：
它或者是一颗空树，或者是具有一下性质的二叉查找树：
1. 节点非红即黑。
2. 根节点是黑色。
3. 所有NULL结点称为叶子节点，且认为颜色为黑。
4. 所有红节点的子节点都为黑色。
5. 从任一节点到其叶子节点的所有路径上都包含相同数目的黑节点。

这是一个红黑树的实例图：
![](http://i.imgur.com/hJG1rEs.png)

那么要在红黑树中插入或者删除一个节点的话，就可能会破坏某个性质的约束，这种情况下就需要我们在操作以后对树结构进行重新排序，这块的内容我自己也看了个大概，就不照贴网上资料了，可以看[这里](http://www.cnblogs.com/fornever/archive/2011/12/02/2270692.html)详细了解一下。
## 4.  查找原因

上面红黑树看的我实在头疼，光画图就画了好多。感觉还是理解不够深，索性不去看了。直接去看TreeMap源码：

``` java
  /**TreeMap 插入方法*/
  public V put(K key, V value) {
        Entry<K,V> t = root;
        if (t == null) {
            compare(key, key); // type (and possibly null) check

            root = new Entry<>(key, value, null);
            size = 1;
            modCount++;
            return null;
        }
        int cmp;
        Entry<K,V> parent;
        // split comparator and comparable paths
        Comparator<? super K> cpr = comparator;
        if (cpr != null) {
            do {
                parent = t;
                cmp = cpr.compare(key, t.key);
                if (cmp < 0)
                    t = t.left;
                else if (cmp > 0)
                    t = t.right;
                else
                    return t.setValue(value);
            } while (t != null); //上面场景重现中put时就是在这行死循环了
        }
        else {
            if (key == null)
                throw new NullPointerException();
            Comparable<? super K> k = (Comparable<? super K>) key;
            do {
                parent = t;
                cmp = k.compareTo(t.key);
                if (cmp < 0)
                    t = t.left;
                else if (cmp > 0)
                    t = t.right;
                else
                    return t.setValue(value);
            } while (t != null);
        }
        Entry<K,V> e = new Entry<>(key, value, parent);
        if (cmp < 0)
            parent.left = e;
        else
            parent.right = e;
        fixAfterInsertion(e);
        size++;
        modCount++;
        return null;
    }
```

``` java
/**插入完毕后重新排序符合红黑树规则*/
private void fixAfterInsertion(Entry<K,V> x) {
        x.color = RED;
        while (x != null && x != root && x.parent.color == RED) {
            if (parentOf(x) == leftOf(parentOf(parentOf(x)))) {
                Entry<K,V> y = rightOf(parentOf(parentOf(x)));
                if (colorOf(y) == RED) {
                    setColor(parentOf(x), BLACK);
                    setColor(y, BLACK);
                    setColor(parentOf(parentOf(x)), RED);
                    x = parentOf(parentOf(x));
                } else {
                    if (x == rightOf(parentOf(x))) {
                        x = parentOf(x);
                        rotateLeft(x);
                    }
                    setColor(parentOf(x), BLACK);
                    setColor(parentOf(parentOf(x)), RED);
                    rotateRight(parentOf(parentOf(x)));
                }
            } else {
                Entry<K,V> y = leftOf(parentOf(parentOf(x)));
                if (colorOf(y) == RED) {
                    setColor(parentOf(x), BLACK);
                    setColor(y, BLACK);
                    setColor(parentOf(parentOf(x)), RED);
                    x = parentOf(parentOf(x));
                } else {
                    if (x == leftOf(parentOf(x))) {
                        x = parentOf(x);
                        rotateRight(x);
                    }
                    setColor(parentOf(x), BLACK);
                    setColor(parentOf(parentOf(x)), RED);
                    rotateLeft(parentOf(parentOf(x)));
                }
            }
        }
        root.color = BLACK;
    }
```

``` java
 /**重新排序时左旋方法8*/
 private void rotateLeft(Entry<K,V> p) {
        if (p != null) {
            Entry<K,V> r = p.right;
            p.right = r.left;//上面场景重现中报空指针的位置
            if (r.left != null)
                r.left.parent = p;
            r.parent = p.parent;
            if (p.parent == null)
                root = r;
            else if (p.parent.left == p)
                p.parent.left = r;
            else
                p.parent.right = r;
            r.left = p;
            p.parent = r;
        }
    }
```

``` java
    /**TreeMap移除节点方法 */
public V remove(Object key) {
        Entry<K,V> p = getEntry(key);
        if (p == null)
            return null;

        V oldValue = p.value;
        deleteEntry(p);
        return oldValue;
    }
```

``` java
  /** 移除节点的内部方法，并会重新排序*/
private void deleteEntry(Entry<K,V> p) {
        modCount++;
        size--;

        // If strictly internal, copy successor's element to p and then make p
        // point to successor.
        if (p.left != null && p.right != null) {
            Entry<K,V> s = successor(p);
            p.key = s.key;
            p.value = s.value;
            p = s;
        } // p has 2 children

        // Start fixup at replacement node, if it exists.
        Entry<K,V> replacement = (p.left != null ? p.left : p.right);

        if (replacement != null) {
            // Link replacement to parent
            replacement.parent = p.parent;
            if (p.parent == null)
                root = replacement;
            else if (p == p.parent.left)
                p.parent.left  = replacement;
            else
                p.parent.right = replacement;

            // Null out links so they are OK to use by fixAfterDeletion.
            p.left = p.right = p.parent = null;

            // Fix replacement
            if (p.color == BLACK)
                fixAfterDeletion(replacement);
        } else if (p.parent == null) { // return if we are the only node.
            root = null;
        } else { //  No children. Use self as phantom replacement and unlink.
            if (p.color == BLACK)
                fixAfterDeletion(p);

            if (p.parent != null) {
                if (p == p.parent.left)
                    p.parent.left = null;
                else if (p == p.parent.right)
                    p.parent.right = null;
                p.parent = null;
            }
        }
    }

```

``` java
 /**移除时重新排序 */
 private void fixAfterDeletion(Entry<K,V> x) {
        while (x != root && colorOf(x) == BLACK) {
            if (x == leftOf(parentOf(x))) {
                Entry<K,V> sib = rightOf(parentOf(x));

                if (colorOf(sib) == RED) {
                    setColor(sib, BLACK);
                    setColor(parentOf(x), RED);
                    rotateLeft(parentOf(x));
                    sib = rightOf(parentOf(x));
                }

                if (colorOf(leftOf(sib))  == BLACK &&
                    colorOf(rightOf(sib)) == BLACK) {
                    setColor(sib, RED);
                    x = parentOf(x);
                } else {
                    if (colorOf(rightOf(sib)) == BLACK) {
                        setColor(leftOf(sib), BLACK);
                        setColor(sib, RED);
                        rotateRight(sib);
                        sib = rightOf(parentOf(x));
                    }
                    setColor(sib, colorOf(parentOf(x)));
                    setColor(parentOf(x), BLACK);
                    setColor(rightOf(sib), BLACK);
                    rotateLeft(parentOf(x));
                    x = root;
                }
            } //上面的重现以及@芒果提供的截图都是在这里进入了循环
            else { // symmetric
                Entry<K,V> sib = leftOf(parentOf(x));

                if (colorOf(sib) == RED) {
                    setColor(sib, BLACK);
                    setColor(parentOf(x), RED);
                    rotateRight(parentOf(x));
                    sib = leftOf(parentOf(x));
                }

                if (colorOf(rightOf(sib)) == BLACK &&
                    colorOf(leftOf(sib)) == BLACK) {
                    setColor(sib, RED);
                    x = parentOf(x);
                } else {
                    if (colorOf(leftOf(sib)) == BLACK) {
                        setColor(rightOf(sib), BLACK);
                        setColor(sib, RED);
                        rotateLeft(sib);
                        sib = leftOf(parentOf(x));
                    }
                    setColor(sib, colorOf(parentOf(x)));
                    setColor(parentOf(x), BLACK);
                    setColor(leftOf(sib), BLACK);
                    rotateRight(parentOf(x));
                    x = root;
                }
            }
        }

        setColor(x, BLACK);
    }
```

上面贴出了TreeMap 的put()和remove()方法代码，同时也标注了情景重新中堆栈信息所指向的代码位置。可以看出都是进入了while的循环语句。但是我看着源码去画图最后都没有完成一次删除操作，搞的也是很郁闷，现在我只能猜测死循环的原因是在高并发情况下两个节点相互指向形成闭合。具体是不是这样我还得再看看咯。

**Comment by crazyjohn** [comment]
赞
